<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>language_features_f_sharp</RootNamespace>
        <LangVersion>preview</LangVersion>
        <WarningLevel>3</WarningLevel>
        <NoWarn>FS0057;FS3511</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Variables.fs"/>
        <Compile Include="Conditions.fs"/>
        <Compile Include="Loops.fs"/>
        <Compile Include="Methods.fs"/>
        <Compile Include="Lists.fs"/>
        <Compile Include="Classes.fs"/>
        <Compile Include="Constructors.fs"/>
        <Compile Include="Inheritance.fs"/>
        <Compile Include="Polymorphism.fs"/>
        <Compile Include="Interfaces.fs"/>
        <Compile Include="Generics.fs"/>
        <Compile Include="Dictionary.fs"/>
        <Compile Include="Strings.fs"/>
        <Compile Include="Exceptions.fs"/>
        <Compile Include="Asynchrony.fs"/>
        <Compile Include="Collections.fs"/>
        <Compile Include="Enums.fs"/>
        <Compile Include="Structs.fs"/>
        <Compile Include="Records.fs"/>
        <Compile Include="Delegates.fs"/>
        <Compile Include="Extensions.fs"/>
        <Compile Include="Attributes.fs"/>
        <Compile Include="PolymorphismViaFunctions.fs"/>
        <Compile Include="Tuples.fs"/>
        <Compile Include="Nullability.fs"/>
        <Compile Include="PatternMatching.fs"/>
        <Compile Include="Indexer.fs"/>
        <Compile Include="Operators.fs"/>
        <Compile Include="Iterators.fs"/>
        <Compile Include="Parameters.fs"/>
        <Compile Include="Recursion.fs"/>
        <Compile Include="Immutability.fs"/>
        <Compile Include="FunctionalComposition.fs"/>
        <Compile Include="DiscriminatedUnions.fs"/>
        <Compile Include="ActivePatterns.fs"/>
        <Compile Include="UnitsOfMeasure.fs"/>
        <Compile Include="ComputationExpressions.fs"/>
        <Compile Include="ObjectExpressions.fs"/>
        <Compile Include="SIMD.fs"/>
        <Compile Include="Program.fs"/>
    </ItemGroup>

</Project>
