<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>Language_Features_F_Sharp</RootNamespace>
        <LangVersion>preview</LangVersion>
        <WarningLevel>3</WarningLevel>
        <NoWarn>FS0057;FS3511</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="Variablen.fs"/>
        <Compile Include="Bedingungen.fs"/>
        <Compile Include="Schleifen.fs"/>
        <Compile Include="Methoden.fs"/>
        <Compile Include="Listen.fs"/>
        <Compile Include="Klassen.fs"/>
        <Compile Include="Konstruktor.fs"/>
        <Compile Include="Vererbung.fs"/>
        <Compile Include="Polymorphie.fs"/>
        <Compile Include="Interfaces.fs"/>
        <Compile Include="Generics.fs"/>
        <Compile Include="Woerterbuch.fs"/>
        <Compile Include="Strings.fs"/>
        <Compile Include="Exceptions.fs"/>
        <Compile Include="Asynchronitaet.fs"/>
        <Compile Include="Collections.fs"/>
        <Compile Include="Enums.fs"/>
        <Compile Include="Structs.fs"/>
        <Compile Include="Records.fs"/>
        <Compile Include="Delegates.fs"/>
        <Compile Include="Extensions.fs"/>
        <Compile Include="Attribut.fs"/>
        <Compile Include="Polymorphismus.fs"/>
        <Compile Include="Tupel.fs"/>
        <Compile Include="Nullbarkeit.fs"/>
        <Compile Include="MusterAbgleich.fs"/>
        <Compile Include="Indexer.fs"/>
        <Compile Include="Operatoren.fs"/>
        <Compile Include="Iteratoren.fs"/>
        <Compile Include="Parameter.fs"/>
        <Compile Include="Rekursion.fs"/>
        <Compile Include="Unveraenderlichkeit.fs"/>
        <Compile Include="FunktionaleKomposition.fs"/>
        <Compile Include="DiskriminierteVereinigungen.fs"/>
        <Compile Include="AktiveMuster.fs"/>
        <Compile Include="Masseinheiten.fs"/>
        <Compile Include="Berechnungsausdruecke.fs"/>
        <Compile Include="ObjektAusdruecke.fs"/>
        <Compile Include="Program.fs"/>
    </ItemGroup>

</Project>
